### ISSUE TITLE
Liferay basic example fails on yarn build

### ISSUE THREAD

**Issue by mir333** [lundegaard/react-union#412]
Hi 

I'm trying to build the Liferay basic example. The `yarn start` command works but when I try to create a build it breaks.

Child client:
    Time: 2639ms
    Built at: 15/08/2019 17:39:23
     6 assets
    Entrypoint main = js/runtime.44ea2d0b.bundle.js js/vendor.cddd894f.chunk.js css/main.d3eb3eb6.chunk.css js/main.d3eb3eb6.chunk.js
      [7] ../node_modules/react/index.js 190 bytes {4} [built]
     [57] ../node_modules/react-union/es/react-union.js 16.3 KiB {4} [built]
     [95] ../node_modules/core-js/modules/es6.array.iterator.js 1.09 KiB {4} [built]
    [133] ../node_modules/core-js/modules/es6.regexp.flags.js 201 bytes {4} [built]
    [144] ../node_modules/document-ready/index.js 396 bytes {4} [built]
    [153] multi ../packages/app-demo/src/index 28 bytes {2} [built]
    [154] ../node_modules/core-js/modules/es6.array.copy-within.js 237 bytes {4} [built]
    [156] ../node_modules/core-js/modules/es6.array.fill.js 215 bytes {4} [built]
    [157] ../node_modules/core-js/modules/es6.array.find.js 527 bytes {4} [built]
    [159] ../node_modules/core-js/modules/es6.array.find-index.js 547 bytes {4} [built]
    [160] ../node_modules/core-js/modules/es7.array.flat-map.js 740 bytes {4} [built]
    [162] ../node_modules/core-js/modules/es6.array.from.js 1.6 KiB {4} [built]
    [163] ../node_modules/core-js/modules/es7.array.includes.js 379 bytes {4} [built]
    [166] ../node_modules/core-js/modules/es6.array.of.js 612 bytes {4} [built]
    [314] ../packages/app-demo/src/index.js + 1 modules 7.06 KiB {2} [built]
          | ../packages/app-demo/src/index.js 6.38 KiB [built]
          | ../packages/app-demo/src/components/Root/index.js 33 bytes [built]
        + 728 hidden modules
    
    ERROR in js/@union-liferay/widget-content.8183f60a.chunk.js from UglifyJs
    `warnings` is not a supported option
    
    ERROR in js/@union-liferay/widget-hero.555a40e8.chunk.js from UglifyJs
    `warnings` is not a supported option
    
    ERROR in js/main.d3eb3eb6.chunk.js from UglifyJs
    `warnings` is not a supported option
    
    ERROR in js/runtime.44ea2d0b.bundle.js from UglifyJs
    `warnings` is not a supported option
    
    ERROR in js/vendor.cddd894f.chunk.js from UglifyJs
    `warnings` is not a supported option
    Child extract-css-chunks-webpack-plugin ../node_modules/css-loader/dist/cjs.js??ref--5-1!../packages/app-demo/src/components/Root/Root.css:
        Entrypoint extract-css-chunks-webpack-plugin = *
        [0] ../node_modules/css-loader/dist/cjs.js??ref--5-1!../packages/app-demo/src/components/Root/Root.css 251 bytes {0} [built]
        [1] ../node_modules/css-loader/dist/runtime/api.js 2.35 KiB {0} [built]
[17:39:23] Finished 'build' after 2890 ms
🚀 Starting Liferay AMD loader scripts 🚀
Creating Liferay AMD configuration...
/tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/node_modules/jsonfile/index.js:67
      throw err
      ^

Error: /tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/build/app-demo/assetManifest.json: ENOENT: no such file or directory, open '/tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/build/app-demo/assetManifest.json'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.readFileSync (/tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/node_modules/jsonfile/index.js:61:22)
    at R.forEach.appName (/tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/tools/amdLoaderScripts.js:86:23)
    at forEach (/tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/node_modules/ramda/src/forEach.js:45:5)
    at /tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/node_modules/ramda/src/internal/_checkForMethod.js:22:72
    at /tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/node_modules/ramda/src/internal/_curry2.js:22:18
    at f1 (/tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/node_modules/ramda/src/internal/_curry1.js:18:17)
    at createLiferayConfig (/tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/tools/amdLoaderScripts.js:101:4)
    at Object.<anonymous> (/tmp/react-union/boilerplates/react-union-boilerplate-liferay-basic/tools/amdLoaderScripts.js:106:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tommmyy** [comment]
thank you for reporting it, we will look at it

**Comment by mir333** [comment]
The problem seems to be connected with webpack and uglify. If I put this in the union config the problem goes away unionWebpackConfig.optimization.minimize= false;

**Comment by Flosrn** [comment]
Hello, I have the same error but I don't understand where do you put your minimize option. Can you explain me where you put it ?

**Comment by tommmyy** [comment]
@mir333 we updated a few dependencies, it should work now :)
