### ISSUE TITLE
Liferay basic boilerplate issue with Liferay 7.2

### ISSUE THREAD

**Issue by Flosrn** [lundegaard/react-union#413]
I tried to deploy my amd-loader .jar into my deploy folder of Liferay 7.2 but i encoutered an issue with **elasticsearch** when i open my right panel for import widgets : 

```
2019-08-22 13:04:49.591 ERROR [http-nio-8080-exec-8][ElasticsearchIndexSearcher:169] java.lang.RuntimeException: org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed
java.lang.RuntimeException: org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:133)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:254)
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:101)
	at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$1(InitialSearchPhase.java:210)
	at org.elasticsearch.action.search.InitialSearchPhase$1.doRun(InitialSearchPhase.java:189)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

And when I tried the same steps with the hero-portlet I have an issue with **com.liferay.portal.kernel.portlet.bridges.mvc**: 

```
2019-08-22 13:04:32.747 ERROR [fileinstall-/Users/flo/Documents/Code/liferay/test/liferay-ce-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/Users/flo/Documents/Code/liferay/test/liferay-ce-portal-7.2.0-ga1/osgi/modules/eu.reactunion.boilerplate.hero-portlet-1.0.0.jar
org.osgi.framework.BundleException: Could not resolve module: eu.reactunion.boilerplate.hero-portlet [1073]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.portlet.bridges.mvc; version="[1.0.0,2.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
```

I also tried same things with Liferay 7.1.2-ga3 and I encountered the sames issues, actually it only work fine with Liferay 7.0-ga7.

If someone could help me it would be really cool, thank you.

**Comment by tommmyy** [comment]
see #417
